version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=sqlite:///./app.db
    command: uv run uvicorn backend_api.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      # This 
      - /app/node_modules
      #- ./frontend/node_modules:/app/node_modules
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend

  titiler:
    image: ghcr.io/developmentseed/titiler:latest
    platform: linux/amd64
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data:ro
    environment:
      - TITILER_CACHE_DISABLE=true
      - TITILER_CACHE_TYPE=null
      - GDAL_DISABLE_READDIR_ON_OPEN=FALSE


    command: uvicorn titiler.application.main:app --host 0.0.0.0 --port 8080